apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-oomkilled
  namespace: default
  labels:
    app: test-oomkilled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-oomkilled
  template:
    metadata:
      labels:
        app: test-oomkilled
    spec:
      containers:
      - name: oomkilled-container
        image: python:3.9-slim
        command: ["python", "-c", "import time; print('Allocating memory beyond limit...'); x = ' ' * 50000000; time.sleep(100)"]
        resources:
          limits:
            memory: "10Mi"
          requests:
            memory: "5Mi"
